import Header from '@/modules/admin/components/Header';
import Sidebar from '@/modules/admin/components/Sidebar';
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Image from 'next/image';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="he" dir='rtl'>
      <body className={inter.className}>
        <main>
          <Header/>
            <div className="grid grid-cols-12 bg-white" style={{ paddingTop:'70px'}}>
                <div className="col-span-1" style={{height:'100%'}}>
                    <Sidebar/>
                </div>
                <div className="col-span-11 mb-[900px]" style={{minHeight:'calc(100vh - 70px)'}}>
                    {children}
                </div>
            </div>
        </main>
      </body>
    </html>
  )
}
